### ISSUE TITLE
How do i disable the auto left click when clicking the edit button?

### ISSUE THREAD

**Issue by Crusage** [dpvdberg/FortEZEdit#1]
I love having hold to edit, but would much rather prefer having to hold down the edit key and also holding down left key to select the edits for more control. How would i achieve this?

**Comment by dpvdberg** [comment]
By 'left key' I assume you mean the left mouse button.
In that case, just switch the mouse ID to a number high enough such that mouse inputs are not registered. This should render all mouse events in the program dysfunctional.
Note that the program will now also not be able to reset your edits, as this requires a right mouse button click.

**Comment by Assbusta** [comment]
I have a question regarding this, when its run does it affect the computer performance in any way? Thanks in advance

**Comment by dpvdberg** [comment]
No it should not affect your performance much, if it does, please make a new issue for this
