### ISSUE TITLE
How to use the program?

### ISSUE THREAD

**Issue by Assbusta** [dpvdberg/FortEZEdit#2]
As mentioned in the title, I don't know which file to execute in order to let the program work, what do I need to install in order for it to work properly and which exact steps do I need to follow for the program to work? Thanks in advance. (I'm not a developer, just interested in the concept of this program. AKA a user)

**Comment by dpvdberg** [comment]
Sorry for the extremely late reaction, try to download a release from [here](https://github.com/dpvdberg/FortEZEdit/releases), unpack and execute the binary.
